version: "3.8"

services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: labo-nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    networks:
      kevin-network:

## Router

  mongodb1:
    image: mongo:latest
    container_name: labo-mongodb1
    hostname: mongodb1
    volumes:
        - ./mongodb/init/:/docker-entrypoint-initdb.d/:ro
        - ./mongodb/data1/db/:/data/db/
        - ./mongodb/data1/log/:/var/log/mongodb/
        - ./mongodb/scripts:/scripts
    environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: test
        MONGO_INITDB_DATABASE: test
    ports:
        - "28017:27017"
    command: mongos --port 27017 --configdb configserver/config01:27017,config02:27017 --bind_ip_all
    networks:
      kevin-network:

## Config Server

  config01:
    image: mongo:latest
    command: mongod --port 27017 --configsvr --replSet configserver
    volumes:
      - ./mongodb/scripts:/scripts
    networks:
      kevin-network:
  config02:
    image: mongo:latest
    command: mongod --port 27017 --configsvr --replSet configserver
    volumes:
      - ./mongodb/scripts:/scripts
    networks:
      kevin-network:

## Shards

  shard01a:
    image: mongo:latest
    command: mongod --port 27018 --shardsvr --replSet shard01
    volumes:
      - ./mongodb/scripts:/scripts
    networks:
      kevin-network:
  shard01b:
    image: mongo:latest
    command: mongod --port 27018 --shardsvr --replSet shard01
    volumes:
      - ./mongodb/scripts:/scripts
    networks:
      kevin-network:
  shard02a:
    image: mongo:latest
    command: mongod --port 27019 --shardsvr --replSet shard02
    volumes:
      - ./mongodb/scripts:/scripts
    networks:
      kevin-network:
  shard02b:
    image: mongo:latest
    command: mongod --port 27019 --shardsvr --replSet shard02
    volumes:
      - ./mongodb/scripts:/scripts
    networks:
      kevin-network:


  server1:
    build: ./server1
    container_name: labo-server1
    environment:
      - VIRTUAL_HOST=api.server1.net
      - VIRTUAL_PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - mongodb1
    networks:
      kevin-network:
networks:
  kevin-network:
